spring:
  application:
    name: backend

  datasource:
    url: jdbc:mysql://localhost:3306/repomgt?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
server:
  port: 8090

